<?php

namespace AppBundle\Repository;

/**
 * CompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionRepository extends \Doctrine\ORM\EntityRepository
{
  /**
  * Recherche de la liste des compétitions
  *
  * Author: Delrodie AMOIKON
  * Date: 28/01/2017
  * Since: v1.0
  */
  public function getAdmincalendrier()
  {
      $em = $this->getEntityManager();
      $qb = $em->createQuery('
          SELECT c
          FROM AppBundle:Competition c
          ORDER BY c.datedeb DESC
      ')
      ;
      try {
          $result = $qb->getResult();

          return $result;

      } catch (NoResultException $e) {
          return $e;
      }

  }

  /**
  * Recherche des compétitions actives
  *
  * Author: Delrodie AMOIKON
  * Date: 01/02/2017
  * Since: v1.0
  */
  public function getCompetition()
  {
      $em = $this->getEntityManager();
      $qb = $em->createQuery('
          SELECT c
          FROM AppBundle:Competition c
          WHERE c.statut = :stat
          AND c.datedeb >= :today
          ORDER BY c.datedeb ASC
      ')
        ->setParameter('stat', 1)
        ->setParameter('today', date('Y-m-d', time()))
      ;
      try {
          $result = $qb->getResult();

          return $result;

      } catch (NoResultException $e) {
          return $e;
      }
  }

  /**
  * Recherche de l'article de la rubrique compétition
  *
  * Author: Delrodie AMOIKON
  * Date: 01/02/2017
  * Since: v1.0
  */
  public function getArticle($slug)
  {
      $em = $this->getEntityManager();
      $qb = $em->createQuery('
          SELECT c
          FROM AppBundle:Competition c
          WHERE c.slug LIKE :slug
          AND c.statut = :stat
      ')
        ->setParameter('slug', '%'.$slug.'%')
        ->setParameter('stat', 1)
      ;
      try {
          $result = $qb->getResult();

          return $result;

      } catch (NoResultException $e) {
          return $e;
      }
  }
  

}
