<?php

namespace AppBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
  /**
  * Recherche de la liste des compétitions
  *
  * Author: Delrodie AMOIKON
  * Date: 28/01/2017
  * Since: v1.0
  */
  public function getAdminevenement()
  {
      $em = $this->getEntityManager();
      $qb = $em->createQuery('
          SELECT e
          FROM AppBundle:Evenement e
          ORDER BY e.datedeb DESC
      ')
      ;
      try {
          $result = $qb->getResult();

          return $result;

      } catch (NoResultException $e) {
          return $e;
      }
  }

    /**
    * Recherche des compétitions actives
    *
    * Author: Delrodie AMOIKON
    * Date: 01/02/2017
    * Since: v1.0
    */
    public function getEvenement()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQuery('
            SELECT e
            FROM AppBundle:Evenement e
            WHERE e.statut = :stat
            AND e.datedeb >= :today
            ORDER BY e.datedeb ASC
        ')
          ->setParameter('stat', 1)
          ->setParameter('today', date('Y-m-d', time()))
        ;
        try {
            $result = $qb->getResult();

            return $result;

        } catch (NoResultException $e) {
            return $e;
        }
    }
}
