<?php

namespace AppBundle\Repository;

/**
 * InitiationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InitiationRepository extends \Doctrine\ORM\EntityRepository
{
}
