<?php

namespace AppBundle\Repository;

/**
 * PhotothequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotothequeRepository extends \Doctrine\ORM\EntityRepository
{
}
