<?php

namespace AppBundle\Repository;

/**
 * VideothequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideothequeRepository extends \Doctrine\ORM\EntityRepository
{
}
