app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    path:     /admin
    defaults: { _controller: "AppBundle:Default:admin" }
    methods:  [GET, POST]
