app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    path:     /admin
    defaults: { _controller: "AppBundle:Default:admin" }
    methods:  [GET, POST]

menu_presentation:
    path:     /menu/presentation
    defaults: { _controller: "AppBundle:Menu:presentation" }
    methods:  [GET, POST]

menu_initiation:
    path:     /menu/initiation
    defaults: { _controller: "AppBundle:Menu:initiation" }
    methods:  [GET, POST]

menu_academy:
    path:     /menu/academy
    defaults: { _controller: "AppBundle:Menu:academy" }
    methods:  [GET, POST]

menu_societe:
    path:     /menu/societe
    defaults: { _controller: "AppBundle:Menu:societe" }
    methods:  [GET, POST]

menu_competition:
    path:     /menu/competition
    defaults: { _controller: "AppBundle:Menu:competition" }
    methods:  [GET, POST]

admin_competition_calendrier:
    path:     /admin/calendrier-des-competition
    defaults: { _controller: "AppBundle:Default:calendrier" }
    methods:  [GET, POST]

# Menu Front office
fomenu_presentation:
    path:     /menu-presentation
    defaults: { _controller: "AppBundle:Menu:fopresentation" }
    methods:  [GET, POST]

fomenu_initiation:
    path:     /menu_initiation
    defaults: { _controller: "AppBundle:Menu:foinitiation" }
    methods:  [GET, POST]

fomenu_academy:
    path:     /menu_academy
    defaults: { _controller: "AppBundle:Menu:foacademy" }
    methods:  [GET, POST]


# Article des entites
fo_presentation:
    path:     /presentation/{slug}
    defaults: { _controller: "AppBundle:Fo:presentation" }
    methods:  [GET, POST]

fo_liste_competition:
    path:     /competition-calendrier
    defaults: { _controller: "AppBundle:Default:competition" }
    methods:  [GET, POST]

fo_accueil_competition:
    path:     /competition-accueil
    defaults: { _controller: "AppBundle:Default:accueilcompetition" }
    methods:  [GET, POST]

fo_existence_competition:
    path:     /competition-existence
    defaults: { _controller: "AppBundle:Default:existencecompetition" }
    methods:  [GET, POST]

fo_initiation:
    path:     /initiation-au-golf/{slug}
    defaults: { _controller: "AppBundle:Fo:initiation" }
    methods:  [GET, POST]

fo_academy:
    path:     /golf-academy/{slug}
    defaults: { _controller: "AppBundle:Fo:academy" }
    methods:  [GET, POST]
